config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :emails, only: %i(index show destroy)
  resources :link, only: %i(show)
  resources :messages, only: %i(new edit create update)
  resources :users

  root 'emails#index'

end

app/models/message.rb
class Message < ActiveRecord::Base
  # relationships
  belongs_to :creator, class_name: 'User', foreign_key: :created_by
  has_many :message_users, inverse_of: :message
  accepts_nested_attributes_for :message_users

  # validations
  validates :creator, presence: true
  validates :subject_line, presence: true, length: { maximum: 255 }
  validates :body_content, presence: true, length: { maximum: 65_535 }

  # callbacks
  after_create :create_owner_message_user_record

  protected

  def create_owner_message_user_record
    MessageUser.create(user_id: created_by, message_id: id)
  end
end

app/models/message_user.rb
class MessageUser < ActiveRecord::Base
  # relationships
  belongs_to :message, inverse_of: :message_users
  belongs_to :user

  # validation
  validates :message, presence: true
  validates :user_id, presence: true

  # callbacks
  before_validation :initialize_some_fields, on: :create
  after_create :enqueue_email

  # scopes
  scope :all_in_order, -> { order(user_id: :asc, viewed: :desc, message_id: :desc) }
  scope :all_viewed, -> { where(viewed: true) }
  scope :all_not_viewed, -> { where(viewed: false) }
  scope :all_inbox, -> { includes(:message).where('messages.created_by != message_users.user_id').references(:message) }
  scope :all_sent, -> { includes(:message).where('messages.created_by = message_users.user_id').references(:message) }

  protected

  def enqueue_email
    SendNotificationsJob.set(wait: 5.seconds).perform_later(id) unless user_id == message.created_by
  end

  def initialize_some_fields
    self.uuid = SecureRandom.urlsafe_base64(20)
    self.viewed = false
    true
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # relationships
  has_many :inbox_messages, through: :message_users, source: :message
  has_many :message_users
  has_many :sent_messages, foreign_key: :created_by, class_name: 'Message'

  # validation
  validates :first_name, presence: true
  validates :last_name, presence: true

  # scopes
  scope :all_in_order, -> { order(:last_name, :first_name) }

  # instance methods
  def admin?
    false # TODO: implement hierarchical authorisations later
  end

  def full_name
    (first_name + ' ' + last_name).titleize
  end

  def full_name_and_email
    "#{full_name} (#{email})"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :authenticate_user! # Devise's way to ensure users are logged in
end

app/controllers/emails_controller.rb
class EmailsController < ApplicationController
  before_action :set_singleton, only: %i(show destroy)

  # GET /messages
  def index
    @sent_message_users = current_user.message_users.all_sent.all_in_order
    @inbox_message_users = current_user.message_users.all_inbox.all_in_order
  end

  # GET /messages/1
  def show
    @message_user.update_attribute(:viewed, true)
  end

  # DELETE /messages/1
  def destroy
    if @message_user.destroy
      flash[:success] = I18n.t('controllers.emails.destroy.success')
    else
      flash[:error] = I18n.t('controllers.emails.destroy.error')
    end
    redirect_to emails_url
  end

  private

  def set_singleton
    @message_user = current_user.message_users.find(params[:id])
  end
end

app/controllers/link_controller.rb
class LinkController < ApplicationController
  def show
    message_user = current_user.message_users.find_by(uuid: params[:id])
    if message_user
      redirect_to email_url(message_user.id)
    else
      flash[:error] = I18n.t('controllers.link.show.error')
      redirect_to emails_url
    end
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_singleton, only: %i(edit update destroy)
  before_action :set_users

  # GET /messages/new
  def new
    @message = current_user.sent_messages.new
    @message.message_users.build(user_id: User.find_by(email: params[:to])&.id)
  end

  # GET /messages/1/edit
  def edit
  end

  # POST /messages
  def create
    @message = current_user.sent_messages.new(message_params)
    if @message.save
      flash[:success] = I18n.t('controllers.emails.create.success')
      redirect_to emails_url
    else
      flash[:error] = I18n.t('controllers.emails.create.error')
      render :new
    end
  end

  # PATCH/PUT /messages/1
  def update
    if @message.update(message_params)
      flash[:success] = I18n.t('controllers.emails.update.success')
      redirect_to emails_url
    else
      flash[:error] = I18n.t('controllers.emails.update.error')
      render :edit
    end
  end

  protected

  def message_params
    params.require(:message).permit(:subject_line, :body_content, message_users_attributes: [:user_id])
  end

  def set_singleton
    @message = current_user.sent_messages.find(params[:id])
  end

  def set_users
    @users = User.where.not(id: current_user.id).all_in_order
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :get_singleton, only: %i(show edit update destroy)

  def index
    @users = User.all_in_order
  end

  def show
  end

  def new
    @user = User.new
  end

  def edit
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = I18n.t('controllers.users.create.success')
      redirect_to @user
    else
      flash.now[:error] = I18n.t('controllers.users.create.error')
      render :new
    end
  end

  def update
    if @user.update_attributes(user_params)
      flash[:success] = I18n.t('controllers.users.update.success')
      redirect_to @user
    else
      flash.now[:error] = I18n.t('controllers.users.update.error')
      render :edit
    end
  end

  def destroy
    if @user.destroy
      flash[:success] = I18n.t('controllers.users.destroy.success')
      redirect_to new_user_session_url
    else
      flash[:error] = I18n.t('controllers.users.destroy.error')
      redirect_to users_url
    end
  end

  protected

  def get_singleton
    if current_user&.admin?
      @user = User.find(params[:id])
    else
      @user = current_user
    end
  end

  def user_params
    params.require(:user).permit(:email, :first_name, :last_name, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def message_viewed_or_not(viewed)
    if viewed
      content_tag(:span, t('views.general.viewed'), class: 'label label-success')
    else
      content_tag(:span, t('views.general.not_viewed'), class: 'label label-info')
    end
  end
end

app/views/layouts/_flash_messages.html.slim
- if flash[:success]
  p.alert.alert-success = flash[:success]
- elsif flash[:notice]
  p.alert.alert-info = flash[:notice]
- elsif flash[:alert]
  p.alert.alert-warning = flash[:alert]
- elsif flash[:error]
  p.alert.alert-danger = flash[:error]

app/views/layouts/_navbar.html.slim
nav.navbar.navbar-default.navbar-fixed-top
  .container
    .navbar-header
      button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar"
        span class="sr-only" Toggle navigation</span>
        - 3.times do
          span.icon-bar
      = link_to 'Email Project', root_url, class: 'navbar-brand'

    #navbar.navbar-collapse.collapse
      ul.nav.navbar-nav
        li class="#{controller_name == 'emails' ? 'active' : ''}"
          = link_to t('views.emails.index.h1'), emails_url
        li class="#{controller_name == 'users' ? 'active' : ''}"
          = link_to t('views.users.index.h1'), users_url
        li.dropdown
          = link_to '#', data: { toggle: 'dropdown'}, role: 'button', class: 'dropdown-toggle', aria: { haspopup: true, expanded: false } do
            = t('views.navbar.contact')
            span.caret
          ul.dropdown-menu
            li = link_to t('views.navbar.linkedin'), 'https://ie.linkedin.com/in/danlaffan', target: '_blank'
            li = link_to t('views.navbar.website'), 'http://danlaffan.com', target: '_blank'
      ul.nav.navbar-nav.navbar-right
        - if current_user
          li = link_to t('views.navbar.profile'), current_user, class: 'active'
          li = link_to t('views.navbar.log_out'), destroy_user_session_url, method: :delete
        - else
          li = link_to t('views.navbar.sign_in'), new_user_session_url
          li = link_to t('views.navbar.sign_up'), new_user_registration_url, class: 'active'

app/views/layouts/application.html.slim
doctype 5
html lang="en"
  head
    meta charset="utf-8"
    meta http-equiv="X-UA-Compatible" content="IE=edge"
    meta name="viewport" content="width=device-width, initial-scale=1"

    title Email Service
    meta name="author" content='Dan Laffan'
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => false
    = javascript_include_tag 'application', 'data-turbolinks-track' => false
    = csrf_meta_tags

    /! HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries
    /! WARNING: Respond.js doesn't work if you view the page via file://
    /[if lt IE 9]
      script src='https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js'
      script src='https://oss.maxcdn.com/respond/1.4.2/respond.min.js'

  body id="page-#{controller_name}-#{action_name}"
    = render partial: 'layouts/navbar'
    .container
      .row
        .col-xs-12
          = render partial: 'layouts/flash_messages'
          = yield

app/views/messages/_form.html.slim
.well
  = form_for @message, html: { class: 'form-horizontal' } do |f|
    = render partial: 'shared/error_messages', locals: { item: @message }

    - if f.object.id.blank?
      = f.fields_for :message_users do |mu|
        #message-users
          .form-group
            = mu.label :user_id, t('views.emails.index.to'), class: 'control-label col-sm-3'
            .col-sm-7
              = mu.collection_select :user_id, @users, :id, :full_name_and_email,
                      { include_blank: t('views.general.please_select') }, { class: 'form-control' }
            .col-sm-1
              a.btn.btn-block.btn-info.user-remove-button
                .glyphicon.glyphicon-remove
            .col-sm-1
              a.btn.btn-block.btn-success.user-add-button
                .glyphicon.glyphicon-plus
    - else
      .form-group
        label.control-label.col-sm-3 = t('views.emails.index.to')
        .col-sm-9
          = f.fields_for :message_users do |mu|
            - unless mu.object.user_id == f.object.created_by
              p.form-control-static
                => link_to mu.object.user.full_name_and_email, new_message_url(to: mu.object.user.email)
                = message_viewed_or_not(mu.object.viewed)

    .form-group
      = f.label :subject_line, t('views.emails.form.subject_line'), class: 'control-label col-sm-3'
      .col-sm-9
        = f.text_field :subject_line, class: 'form-control'

    .form-group
      = f.label :body_content, t('views.emails.form.body_content'), class: 'control-label col-sm-3'
      .col-sm-9
        = f.text_area :body_content, class: 'form-control', rows: 8

    .form-group
      .col-sm-9.col-sm-offset-3
        => f.submit t('views.general.save'), class: 'btn btn-success'
        = link_to t('views.general.cancel'), emails_url

app/views/messages/edit.html.slim
h1 = t('views.emails.edit.h1')
= render partial: 'form'

app/views/messages/new.html.slim
h1 = t('views.emails.new.h1')
= render partial: 'form'

app/views/shared/_error_messages.html.slim
- if item.errors.any?
   .panel.panel-danger
     .panel-heading
       = t('views.general.error_message', count: item.errors.keys.count)
     .panel-body
       ul
         - item.errors.full_messages.each do |msg|
           li = msg

app/views/users/_form.html.slim
.well
  = form_for @user, html: { class: 'form-horizontal' } do |f|
    = render partial: 'shared/error_messages', locals: { item: @user }

    .form-group
      = f.label :email, t('views.users.form.email'), class: 'control-label col-sm-3'
      .col-sm-9
        = f.email_field :email, class: 'form-control'

    .form-group
      = f.label :first_name, t('views.users.form.first_name'), class: 'control-label col-sm-3'
      .col-sm-9
        = f.text_field :first_name, class: 'form-control'

    .form-group
      = f.label :last_name, t('views.users.form.last_name'), class: 'control-label col-sm-3'
      .col-sm-9
        = f.text_field :last_name, class: 'form-control'

    .form-group
      = f.label :password, t('views.users.form.password'), class: 'control-label col-sm-3'
      .col-sm-9
        = f.password_field :password, class: 'form-control'

    .form-group
      .col-sm-9.col-sm-offset-3
        => f.submit t('views.general.save'), class: 'btn btn-success'
        = link_to t('views.general.cancel'), users_url

app/views/users/edit.html.slim
h1 = t('views.users.edit.h1')
= render partial: 'form'

app/views/users/index.html.slim
h1 = t('views.users.index.h1')
table.table.table-responsive.table-striped
  thead
    tr
      th = t('views.users.form.name')
      th = t('views.users.form.email')
      th
  tbody
    - @users.each do |user|
      tr
        td = link_to user.full_name, user
        td = link_to user.email, user
        td.text-right
          - if user.id == current_user.id
            = link_to t('views.users.index.delete'), user,
                    method: :delete, data: { confirm: t('views.general.delete_confirm') }, class: 'btn btn-xs btn-danger'

- if current_user&.admin?
  = link_to t('views.users.index.new'), new_user_url, class: 'btn btn-success'

app/views/users/new.html.slim
h1 = t('views.users.new.h1')
= render partial: 'form'

app/views/users/show.html.slim
h1 = t('views.users.show.h1', { email: @user.email} )

table.table.table-bordered.table-responsive.table-striped
  tr
    th.col-sm-3 = t('views.users.form.email')
    td.col-sm-9 = @user.email
  tr
    th = t('views.users.form.name')
    td = @user.full_name
  tr
    th = t('views.users.form.id')
    td = @user.id

p
  => link_to t('views.general.back'), users_url, class: 'btn btn-info'
  = link_to t('views.general.edit'), edit_user_url(@user), class: 'btn btn-warning'